### ISSUE TITLE
Template clone fails

### ISSUE THREAD

**Issue by vfebvre** [ManageIQ/manageiq-providers-ibm_power_hmc#71]
Template clone fails

Steps to reproduce
- Select a template from either the Template list or detailed view. From the Lifecycle menu, click on "Clone selected Template" or "Clone this template".
- Fill in the "template name" field on the "Clone Template" form.
- Submit form.

Results:
 - The list of request has a new entry wrongly described as "Publish" instead of "Clone".
 - It ends up in error.
 - EVM log:
```
[----] E, [2022-08-05T16:24:26.765649 #34267:add4] ERROR -- evm: Q-task_id([r8_miq_provision_8]) MIQ(ManageIQ::Providers::IbmPowerHmc::InfraManager::Provision#provision_error) [[NoMethodError]: undefined method ```make_template' for #<ManageIQ::Providers::IbmPowerHmc::InfraManager::Template:0x000001003c32c1b0>
```

Believed to be caused by https://github.com/ManageIQ/manageiq-ui-classic/pull/8377 : Template clone requests are now of type "clone_to_template" and not "clone_to_vm" anymore
On the HMC Provider, "clone_to_template" is currently treated as a request to create a template from a VM. It calls make_template, which is not implemented in the Template class

**Comment by Fryguy** [comment]
@vfebvre Is this fixed via #72?

**Comment by vfebvre** [comment]
@Fryguy Yes, correct, this issue was fixed by #72. I do not have the rights to add PRs to issues on this repo, but otherwise, this issue can be closed.
